### ISSUE TITLE
Sub-pantalla turno Game

### ISSUE THREAD

**Issue by 841723** [UNIZAR-30226-2024-01/front-end-web#16]
Crear una interfaz para gestionar
-  tirar dados
- ver a que habitaciones/casillas puedes moverte
- al entrar en una habitación elegir PERSONAJE y ARMA al que acusar

Chat, Tarjeta y Cartas deben seguir estando disponibles

**Comment by 841723** [comment]
Quizás hacerse oscureciéndose el fondo y utilizar toda la pantalla

**Comment by 841723** [comment]
se va a ocurecer el fondo, e ir poniendo 

1. dados
2. elección de casilla/habitación a la que ir
3. elección de sospecha, si esta en habitación

**Comment by javisin22** [comment]
Añadir contador de tiempo restante de ronda (una cuenta atrás, o si es fácil un círculo verde que se va coloreando de blanco en sentido de agujas del reloj para dar sensación de que se está borrando)

**Comment by 841723** [comment]
añadido el HTML necesario
falta estilizar, elegir casilla en tablero y conectar con back-end
