### ISSUE TITLE
arreglar bfs

### ISSUE THREAD

**Issue by 841723** [UNIZAR-30226-2024-01/front-end-web#39]
![image](https://github.com/UNIZAR-30226-2024-01/front-end-web/assets/118764694/2712998a-ef75-46af-90f2-13d30137b0e6)
al bloquear a un usuario, este puede atravesarlo. NO DEBERIA SER ASI

**Comment by javisin22** [comment]
Ya se bloquea el paso pero hay problemas cuando se bloquea a un jugador
