### ISSUE TITLE
Integración de web-sockets para el chat de discusión

### ISSUE THREAD

**Issue by javisin22** [UNIZAR-30226-2024-01/front-end-web#5]
Se debe de añadir la funcionalidad de los web-sockets al chat de la aplicación para poder ser capaces de difundir los mensajes enviados a todos los jugadores, y recibir los de estos.

**Comment by 841723** [comment]
se ha creado el cliente chat, siendo capaz de enviar mensajes (tanto texto como gifs mandados como URL de https://media.tenor.com/_id de la imagen_) e interpretar y mostrar mensajes recibidos (se interpretan los enlaces de tenor como imagenes)

**Comment by 841723** [comment]
se ha creado el cliente chat, siendo capaz de enviar mensajes (tanto texto como gifs mandados como URL de https://media.tenor.com/_id de la imagen_) e interpretar y mostrar mensajes recibidos (se interpretan los enlaces de tenor como imagenes)
